package com.spring.ecommerce_management.domain;
// Generated Jul 20, 2018 10:14:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerRegi generated by hbm2java
 */
@Entity
@Table(name="customer_regi"
    ,catalog="changed"
)
public class CustomerRegi  implements java.io.Serializable {


     private Integer customerId;
     private String firstName;
     private String lastName;
     private String gender;
     private String customerCity;
     private String customerAddress;
     private String customerMobile;
     private String customerEmail;
     private Date joinDate;
     private String password;
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<ProductOrder> productOrders = new HashSet<ProductOrder>(0);

    public CustomerRegi() {
    }

	
    public CustomerRegi(String firstName, String lastName, String gender, String customerCity, String customerAddress, String customerMobile, String customerEmail, Date joinDate, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.customerCity = customerCity;
        this.customerAddress = customerAddress;
        this.customerMobile = customerMobile;
        this.customerEmail = customerEmail;
        this.joinDate = joinDate;
        this.password = password;
    }
    public CustomerRegi(String firstName, String lastName, String gender, String customerCity, String customerAddress, String customerMobile, String customerEmail, Date joinDate, String password, Set<Payment> payments, Set<ProductOrder> productOrders) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.customerCity = customerCity;
       this.customerAddress = customerAddress;
       this.customerMobile = customerMobile;
       this.customerEmail = customerEmail;
       this.joinDate = joinDate;
       this.password = password;
       this.payments = payments;
       this.productOrders = productOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customer_id", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="first_name", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="gender", nullable=false, length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="customer_city", nullable=false, length=45)
    public String getCustomerCity() {
        return this.customerCity;
    }
    
    public void setCustomerCity(String customerCity) {
        this.customerCity = customerCity;
    }

    
    @Column(name="customer_address", nullable=false, length=45)
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    
    @Column(name="customer_mobile", nullable=false, length=45)
    public String getCustomerMobile() {
        return this.customerMobile;
    }
    
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }

    
    @Column(name="customer_email", nullable=false, length=45)
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="join_date", nullable=false, length=10)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegi")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegi")
    public Set<ProductOrder> getProductOrders() {
        return this.productOrders;
    }
    
    public void setProductOrders(Set<ProductOrder> productOrders) {
        this.productOrders = productOrders;
    }




}


