package com.spring.ecommerce_management.domain;
// Generated Jul 20, 2018 10:14:47 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="order_details"
    ,catalog="changed"
)
public class OrderDetails  implements java.io.Serializable {


     private Integer orderDetailId;
     private ProductOrder productOrder;
     private int orderQty;

    public OrderDetails() {
    }

    public OrderDetails(ProductOrder productOrder, int orderQty) {
       this.productOrder = productOrder;
       this.orderQty = orderQty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_detail_id", unique=true, nullable=false)
    public Integer getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public ProductOrder getProductOrder() {
        return this.productOrder;
    }
    
    public void setProductOrder(ProductOrder productOrder) {
        this.productOrder = productOrder;
    }

    
    @Column(name="order_qty", nullable=false)
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }




}


