package com.spring.ecommerce_management.domain;
// Generated Jul 20, 2018 10:14:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="changed"
)
public class Payment  implements java.io.Serializable {


     private Integer paymentId;
     private CustomerRegi customerRegi;
     private ProductOrder productOrder;
     private String paymentType;
     private Date paymentDate;
     private double discount;
     private double grandTotal;
     private String deliveryZone;
     private double netpayment;
     private String paymentStatus;
     private String deliveryAddress;
     private Set<Sale> sales = new HashSet<Sale>(0);

    public Payment() {
    }

	
    public Payment(CustomerRegi customerRegi, ProductOrder productOrder, String paymentType, Date paymentDate, double discount, double grandTotal, String deliveryZone, double netpayment, String paymentStatus, String deliveryAddress) {
        this.customerRegi = customerRegi;
        this.productOrder = productOrder;
        this.paymentType = paymentType;
        this.paymentDate = paymentDate;
        this.discount = discount;
        this.grandTotal = grandTotal;
        this.deliveryZone = deliveryZone;
        this.netpayment = netpayment;
        this.paymentStatus = paymentStatus;
        this.deliveryAddress = deliveryAddress;
    }
    public Payment(CustomerRegi customerRegi, ProductOrder productOrder, String paymentType, Date paymentDate, double discount, double grandTotal, String deliveryZone, double netpayment, String paymentStatus, String deliveryAddress, Set<Sale> sales) {
       this.customerRegi = customerRegi;
       this.productOrder = productOrder;
       this.paymentType = paymentType;
       this.paymentDate = paymentDate;
       this.discount = discount;
       this.grandTotal = grandTotal;
       this.deliveryZone = deliveryZone;
       this.netpayment = netpayment;
       this.paymentStatus = paymentStatus;
       this.deliveryAddress = deliveryAddress;
       this.sales = sales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public CustomerRegi getCustomerRegi() {
        return this.customerRegi;
    }
    
    public void setCustomerRegi(CustomerRegi customerRegi) {
        this.customerRegi = customerRegi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public ProductOrder getProductOrder() {
        return this.productOrder;
    }
    
    public void setProductOrder(ProductOrder productOrder) {
        this.productOrder = productOrder;
    }

    
    @Column(name="payment_type", nullable=false, length=45)
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="payment_date", nullable=false, length=10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="discount", nullable=false, precision=22, scale=0)
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }

    
    @Column(name="grand_total", nullable=false, precision=22, scale=0)
    public double getGrandTotal() {
        return this.grandTotal;
    }
    
    public void setGrandTotal(double grandTotal) {
        this.grandTotal = grandTotal;
    }

    
    @Column(name="delivery_zone", nullable=false, length=45)
    public String getDeliveryZone() {
        return this.deliveryZone;
    }
    
    public void setDeliveryZone(String deliveryZone) {
        this.deliveryZone = deliveryZone;
    }

    
    @Column(name="netpayment", nullable=false, precision=22, scale=0)
    public double getNetpayment() {
        return this.netpayment;
    }
    
    public void setNetpayment(double netpayment) {
        this.netpayment = netpayment;
    }

    
    @Column(name="payment_status", nullable=false, length=45)
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    
    @Column(name="delivery_address", nullable=false, length=45)
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payment")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }




}


