package com.spring.ecommerce_management.domain;
// Generated Jul 20, 2018 10:14:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductOrder generated by hbm2java
 */
@Entity
@Table(name="product_order"
    ,catalog="changed"
)
public class ProductOrder  implements java.io.Serializable {


     private Integer orderId;
     private CustomerRegi customerRegi;
     private Product product;
     private Purchase purchase;
     private String orderItem;
     private Date orderDate;
     private int itemQty;
     private double price;
     private double totalPrice;
     private String orderStatus;
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public ProductOrder() {
    }

	
    public ProductOrder(CustomerRegi customerRegi, Product product, Purchase purchase, String orderItem, Date orderDate, int itemQty, double price, double totalPrice, String orderStatus) {
        this.customerRegi = customerRegi;
        this.product = product;
        this.purchase = purchase;
        this.orderItem = orderItem;
        this.orderDate = orderDate;
        this.itemQty = itemQty;
        this.price = price;
        this.totalPrice = totalPrice;
        this.orderStatus = orderStatus;
    }
    public ProductOrder(CustomerRegi customerRegi, Product product, Purchase purchase, String orderItem, Date orderDate, int itemQty, double price, double totalPrice, String orderStatus, Set<Payment> payments, Set<OrderDetails> orderDetailses) {
       this.customerRegi = customerRegi;
       this.product = product;
       this.purchase = purchase;
       this.orderItem = orderItem;
       this.orderDate = orderDate;
       this.itemQty = itemQty;
       this.price = price;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.payments = payments;
       this.orderDetailses = orderDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public CustomerRegi getCustomerRegi() {
        return this.customerRegi;
    }
    
    public void setCustomerRegi(CustomerRegi customerRegi) {
        this.customerRegi = customerRegi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purchase_id", nullable=false)
    public Purchase getPurchase() {
        return this.purchase;
    }
    
    public void setPurchase(Purchase purchase) {
        this.purchase = purchase;
    }

    
    @Column(name="order_item", nullable=false, length=46)
    public String getOrderItem() {
        return this.orderItem;
    }
    
    public void setOrderItem(String orderItem) {
        this.orderItem = orderItem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="order_date", nullable=false, length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="item_qty", nullable=false)
    public int getItemQty() {
        return this.itemQty;
    }
    
    public void setItemQty(int itemQty) {
        this.itemQty = itemQty;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="total_price", nullable=false, precision=22, scale=0)
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="order_status", nullable=false, length=45)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productOrder")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productOrder")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


