package com.spring.ecommerce_management.domain;
// Generated Jul 20, 2018 10:14:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierInfo generated by hbm2java
 */
@Entity
@Table(name="supplier_info"
    ,catalog="changed"
)
public class SupplierInfo  implements java.io.Serializable {


     private Integer supplierId;
     private String supplierName;
     private String supplierAddress;
     private String supplierCity;
     private String supplierState;
     private int supplierZip;
     private String supplierEmail;
     private String supplierCompany;
     private Date supplierJoinDate;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public SupplierInfo() {
    }

	
    public SupplierInfo(String supplierName, String supplierAddress, String supplierCity, String supplierState, int supplierZip, String supplierEmail, String supplierCompany, Date supplierJoinDate) {
        this.supplierName = supplierName;
        this.supplierAddress = supplierAddress;
        this.supplierCity = supplierCity;
        this.supplierState = supplierState;
        this.supplierZip = supplierZip;
        this.supplierEmail = supplierEmail;
        this.supplierCompany = supplierCompany;
        this.supplierJoinDate = supplierJoinDate;
    }
    public SupplierInfo(String supplierName, String supplierAddress, String supplierCity, String supplierState, int supplierZip, String supplierEmail, String supplierCompany, Date supplierJoinDate, Set<Purchase> purchases) {
       this.supplierName = supplierName;
       this.supplierAddress = supplierAddress;
       this.supplierCity = supplierCity;
       this.supplierState = supplierState;
       this.supplierZip = supplierZip;
       this.supplierEmail = supplierEmail;
       this.supplierCompany = supplierCompany;
       this.supplierJoinDate = supplierJoinDate;
       this.purchases = purchases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="supplier_id", unique=true, nullable=false)
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    
    @Column(name="supplier_name", nullable=false, length=45)
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    
    @Column(name="supplier_address", nullable=false, length=45)
    public String getSupplierAddress() {
        return this.supplierAddress;
    }
    
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }

    
    @Column(name="supplier_city", nullable=false, length=45)
    public String getSupplierCity() {
        return this.supplierCity;
    }
    
    public void setSupplierCity(String supplierCity) {
        this.supplierCity = supplierCity;
    }

    
    @Column(name="supplier_state", nullable=false, length=45)
    public String getSupplierState() {
        return this.supplierState;
    }
    
    public void setSupplierState(String supplierState) {
        this.supplierState = supplierState;
    }

    
    @Column(name="supplier_zip", nullable=false)
    public int getSupplierZip() {
        return this.supplierZip;
    }
    
    public void setSupplierZip(int supplierZip) {
        this.supplierZip = supplierZip;
    }

    
    @Column(name="supplier_email", nullable=false, length=45)
    public String getSupplierEmail() {
        return this.supplierEmail;
    }
    
    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }

    
    @Column(name="supplier_company", nullable=false, length=45)
    public String getSupplierCompany() {
        return this.supplierCompany;
    }
    
    public void setSupplierCompany(String supplierCompany) {
        this.supplierCompany = supplierCompany;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="supplier_join_date", nullable=false, length=10)
    public Date getSupplierJoinDate() {
        return this.supplierJoinDate;
    }
    
    public void setSupplierJoinDate(Date supplierJoinDate) {
        this.supplierJoinDate = supplierJoinDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supplierInfo")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


